#!/bin/bash
#chkconfig: 2345 88 99
#给脚本加注释默认在2345级别是启动的，88代表启动的顺序，99代表关机时关闭的顺序(最大值不能超过99)
######
case $1 in

start)
	/usr/sbin/httpd &>/dev/null
	if
	[ $? -eq 0 ];then
		echo "${0}启动成功"
	else
		echo "请检查是否已经启动/启动失败"
	fi
;;
stop)
	kill `cat /var/run/httpd/httpd.pid` &>/dev/null
	if
	[ $? -eq 0 ];then
		echo "${0}停止成功"
	else
		echo "$0{}请检查是否已经停止/停止失败"
	fi
;;
restart)
	kill `cat /var/run/httpd/httpd.pid` &>/dev/null
	if
	[ $? -eq 0 ];then
		echo "${0}停止成功"
	else
		echo "${0}请检查是否已经停止/停止失败"
	fi
	sleep 0.5
	/usr/sbin/httpd &>/dev/null	&>/dev/null
	if
	[ $? -eq 0 ];then
	echo "$0启动成功"
	else
		echo "${0}检查是否已经启动/启动失败"
	fi
;;
status)
	if [ -f /var/run/httpd/httpd.pid ];then
	echo "${0}已经启动"
	else
		echo "${0}已死"
	fi
;;
*)
	echo "用法${0}请加{start|stop|restart|status}"
;;
esac
